SELECT C.MODELO AS 'MODELO CARRO',CRC.TIPO AS 'TIPO CARROCERIA',CRC.STATUS AS 'STATUS CARROCERIA',
                   INTR.VOLANTE AS 'MODELO VOLANTE', INTR.BANCOS AS 'TIPO BANCO', TRNSM.TIPO AS 'TIPO TRANSMISSÃO'
                   FROM CARRO AS C  
                   INNER JOIN CARROCERIA AS CRC
                   INNER JOIN INTERIOR AS INTR
                   INNER JOIN TRANSMISSAO AS TRNSM
                   WHERE (CRC.ID_CARROCERIA = C.ID_CARROCERIA AND (CRC.COR = 'VERMELHO' OR CRC.COR = 'PRATA' 
                   OR CRC.COR = 'PRETO' OR CRC.COR = 'AZUL')) AND 
                   (INTR.ID_INTERIOR = C.ID_INTERIOR AND (INTR.BANCOS = 'COURO' OR INTR.BANCOS = 'TECIDO')) AND
                   (TRNSM.ID_TRANSMISSAO = C.ID_TRANSMISSAO AND 
                   (TRNSM.TIPO = 'AUTOMATICO' OR TRNSM.TIPO = 'AUTOMATIZADO')) 
                   ORDER BY C.MODELO;

SET FOREIGN_KEY_CHECKS = 0;
SET bulk_insert_buffer_size = 1024 * 1024 * 256;

LOAD DATA LOCAL INFILE 'mass_tabela_fatos.csv' INTO TABLE CARRO FIELDS TERMINATED BY ';' (MODELO, ID_CARROCERIA, ID_MOTOR, ID_ELETRICA, ID_RODAS, ID_VIDROS, ID_TRANSMISSAO, ID_INTERIOR);

SET FOREIGN_KEY_CHECKS = 1;
