CREATE DATABASE PROJETO_BANCO_2;
USE PROJETO_BANCO_2

CREATE TABLE IF NOT EXISTS CARROCERIA(
	ID_CARROCERIA INT PRIMARY KEY AUTO_INCREMENT,
	MATERIAL VARCHAR(45),
	TIPO VARCHAR(45),
	ALTURA INT,
	LARGURA INT,
	BLINDAGEM CHAR(4),
	COR VARCHAR(45),
	QTD_FAROL INT,
	MOD_FAROL VARCHAR(45),
	STATUS VARCHAR(20)
) ENGINE = innodb;

CREATE TABLE IF NOT EXISTS MOTOR(
	ID_MOTOR INT PRIMARY KEY AUTO_INCREMENT,
	TIPO VARCHAR(45),
	QTD_CILINDROS INT,
	QTD_POTENCIA INT,
	QTD_LITRAGEM VARCHAR(10),
	QTD_VALVULAS INT,
	QTD_TORQUE FLOAT,
	SOBREALIM VARCHAR(45),
	TIPO_ESCAPE VARCHAR(45),
	STATUS VARCHAR(20)
) ENGINE = innodb;

CREATE TABLE IF NOT EXISTS ELETRICA(
	ID_ELETRICA INT PRIMARY KEY AUTO_INCREMENT,
	MOD_CHICOTE VARCHAR(45),
	QTD_SENSORES INT,
	INJ_ELETRONICA CHAR(4),
	BATERIA VARCHAR(45),
	STATUS VARCHAR(20)
) ENGINE = innodb;

CREATE TABLE IF NOT EXISTS TRANSMISSAO(
	ID_TRANSMISSAO INT PRIMARY KEY AUTO_INCREMENT,
	TIPO VARCHAR(45),
	NUM_MARCHAS INT,
	TRACAO VARCHAR(45),
	STATUS VARCHAR(20)
) ENGINE = innodb;

CREATE TABLE IF NOT EXISTS INTERIOR(
	ID_INTERIOR INT PRIMARY KEY AUTO_INCREMENT,
	VOLANTE VARCHAR(45),
	PAINEL VARCHAR(45),
	BANCOS VARCHAR(45),
	MOD_MOSTRADORES VARCHAR(45),
	MOD_COMP_BORDO VARCHAR(45),
	MOD_SIST_AC VARCHAR(45),
	STATUS VARCHAR(20)
) ENGINE = innodb;

CREATE TABLE IF NOT EXISTS VIDROS(
	ID_VIDROS INT PRIMARY KEY AUTO_INCREMENT,
	MODELO VARCHAR(45),
	BLINDAGEM CHAR(4),
	OPACIDADE VARCHAR(45),
	STATUS VARCHAR(20)
) ENGINE = innodb;

CREATE TABLE IF NOT EXISTS RODAS(
	ID_RODAS INT PRIMARY KEY AUTO_INCREMENT,
	ARO INT,
	TALA_PNEU FLOAT,
	COR VARCHAR(45),
	STATUS VARCHAR(20)
) ENGINE = innodb;

CREATE TABLE IF NOT EXISTS CARRO(
	ID_CARRO INT PRIMARY KEY AUTO_INCREMENT,
	MODELO VARCHAR(45),
	ID_CARROCERIA INT,
	ID_MOTOR INT,
	ID_ELETRICA INT,
	ID_RODAS INT,
	ID_VIDROS INT,
	ID_TRANSMISSAO INT,
	ID_INTERIOR INT,
	INDEX `FK_CARROCERIA` (`id_carroceria`),
	INDEX `FK_MOTOR` (`id_motor`),
	INDEX `FK_ELETRICA` (`id_eletrica`),
	INDEX `FK_RODAS` (`id_rodas`),
	INDEX `FK_VIDROS` (`id_vidros`),
	INDEX `FK_TRANSMISSAO` (`id_transmissao`),
	INDEX `FK_INTERIOR` (`id_interior`),
	CONSTRAINT `FK_CARROCERIA`
		FOREIGN KEY (`ID_CARROCERIA`)
		REFERENCES
		CARROCERIA (`ID_CARROCERIA`),
	CONSTRAINT `FK_MOTOR`
		FOREIGN KEY (`ID_MOTOR`)
		REFERENCES
		MOTOR (`ID_MOTOR`),
	CONSTRAINT `FK_ELETRICA`
		FOREIGN KEY (`ID_ELETRICA`)
		REFERENCES
		ELETRICA (`ID_ELETRICA`),
	CONSTRAINT `FK_RODAS`
		FOREIGN KEY (`ID_RODAS`)
		REFERENCES
		RODAS (`ID_RODAS`),
	CONSTRAINT `FK_VIDROS`
		FOREIGN KEY (`ID_VIDROS`)
		REFERENCES
		VIDROS (`ID_VIDROS`),
	CONSTRAINT `FK_TRANSMISSAO`
		FOREIGN KEY (`ID_TRANSMISSAO`)
		REFERENCES
		TRANSMISSAO (`ID_TRANSMISSAO`),
	CONSTRAINT `FK_INTERIOR`
		FOREIGN KEY (`ID_INTERIOR`)
		REFERENCES
		INTERIOR (`ID_INTERIOR`)
	
) ENGINE = innodb;
